@BASE_URL = http://localhost:9000

### Upload Files
POST {{BASE_URL}}/api/admin/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary8oAgbDt4vMExMKVh

------WebKitFormBoundary8oAgbDt4vMExMKVh
Content-Disposition: form-data; name="images"; filename="image1.jpg"
Content-Type: image/jpeg

< C:\Users\x06u4\Desktop\image1.jpg

------WebKitFormBoundary8oAgbDt4vMExMKVh
Content-Disposition: form-data; name="images"; filename="image2.png"
Content-Type: image/png

< C:\Users\x06u4\Desktop\image2.png

------WebKitFormBoundary8oAgbDt4vMExMKVh--
