@BASE_URL = http://localhost:9000

### Admin Upload Files
POST {{BASE_URL}}/api/admin/files HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary8oAgbDt4vMExMKVh

------WebKitFormBoundary8oAgbDt4vMExMKVh
Content-Disposition: form-data; name="images"; filename="image1.jpg"
Content-Type: image/jpeg

< C:\Users\a7894\Desktop\helpers\image1.jpg

------WebKitFormBoundary8oAgbDt4vMExMKVh
Content-Disposition: form-data; name="images"; filename="image2.png"
Content-Type: image/png

< C:\Users\a7894\Desktop\helpers\image2.png

------WebKitFormBoundary8oAgbDt4vMExMKVh--
